export const skillCategories = {
  frontend: [
    "React",
    "Vue.js",
    "Angular",
    "Svelte",
    "Solid.js",
    "Astro",
    "TypeScript",
    "JavaScript",
    "HTML5",
    "CSS3",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Ant Design",
    "shadcn/ui",
    "Chakra UI",
    "Styled Components",
    "Emotion",
    "SASS/SCSS",
    "Next.js",
    "Nuxt.js",
    "Remix",
    "SvelteKit",
    "Qwik",
    "Redux",
    "Zustand",
    "Jotai",
    "Recoil",
    "Context API",
    "MobX",
    "Pinia",
    "Vuex",
    "Webpack",
    "Vite",
    "Parcel",
    "Turbopack",
    "esbuild",
    "Rollup",
    "Jest",
    "Vitest",
    "Cypress",
    "Playwright",
    "Testing Library",
    "Storybook",
    "Figma",
    "Framer Motion",
    "Three.js",
    "Babylon.js",
    "D3.js",
    "Chart.js",
    "PWA",
    "Web Components",
    "GraphQL Client",
    "Apollo Client",
    "React Query",
    "SWR",
    "Axios",
    "Fetch API"
  ],
  backend: [
    "Node.js",
    "Express.js",
    "Fastify",
    "Hapi",
    "NestJS",
    "Koa",
    "Egg.js",
    "Python",
    "Django",
    "FastAPI",
    "Flask",
    "Celery",
    "Java",
    "Spring Boot",
    "Spring Framework",
    "Hibernate",
    "Maven",
    "Gradle",
    "C#",
    ".NET Core",
    "ASP.NET",
    "Entity Framework",
    "Go",
    "Gin",
    "Echo",
    "Fiber",
    "Rust",
    "Actix-web",
    "Rocket",
    "Tokio",
    "Cargo",
    "PHP",
    "Laravel",
    "Symfony",
    "Doctrine",
    "Composer",
    "Ruby",
    "Rails",
    "Sinatra",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Cassandra",
    "DynamoDB",
    "Firebase Realtime DB",
    "Prisma",
    "TypeORM",
    "Sequelize",
    "SQLAlchemy",
    "Mongoose",
    "Docker",
    "Kubernetes",
    "Docker Compose",
    "AWS",
    "Azure",
    "Google Cloud",
    "DigitalOcean",
    "Heroku",
    "Railway",
    "Vercel",
    "Netlify",
    "GraphQL",
    "REST API",
    "WebSocket",
    "gRPC",
    "Message Queue",
    "RabbitMQ",
    "Kafka",
    "Redis Queue",
    "Jest",
    "Mocha",
    "Pytest",
    "JUnit",
    "Git",
    "GitHub Actions",
    "GitLab CI/CD",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Nginx",
    "Apache",
    "PM2",
    "Supervisor"
  ],
  fullstack: [
    "MERN Stack",
    "MEAN Stack",
    "LAMP Stack",
    "JAM Stack",
    "T3 Stack",
    "TALL Stack",
    "MERNG Stack",
    "Next.js",
    "Nuxt.js",
    "Remix",
    "SvelteKit",
    "Astro",
    "Qwik",
    "Laravel",
    "Ruby on Rails",
    "Django",
    "Spring Boot",
    "ASP.NET Core",
    "Firebase",
    "Supabase",
    "Auth0",
    "Clerk",
    "NextAuth.js",
    "Passport.js",
    "JWT",
    "OAuth 2.0",
    "SAML",
    "AWS",
    "AWS Lambda",
    "AWS RDS",
    "AWS S3",
    "AWS DynamoDB",
    "AWS EC2",
    "Azure",
    "Azure App Service",
    "Azure SQL Database",
    "Azure Functions",
    "Google Cloud",
    "Google Cloud Run",
    "Google Cloud SQL",
    "Heroku",
    "Vercel",
    "Netlify",
    "Railway",
    "Render",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "REST API",
    "GraphQL",
    "OpenAPI/Swagger",
    "Postman",
    "Insomnia",
    "Docker",
    "Docker Compose",
    "Kubernetes",
    "Helm",
    "Terraform",
    "CloudFormation",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Sentry",
    "DataDog",
    "New Relic",
    "Notion",
    "Linear",
    "Jira",
    "Confluence",
    "Slack API",
    "Stripe API",
    "Twilio",
    "SendGrid",
    "WebRTC",
    "Socket.io",
    "Nginx",
    "Apache",
    "Load Balancing",
    "Caching",
    "CDN",
    "Cloudflare",
    "SEO Optimization",
    "Performance Monitoring",
    "A/B Testing",
    "Analytics"
  ]
} as const;

